import { Center, Container, Flex, Heading, Input, Spacer, Spinner, Text } from "@chakra-ui/react";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { useState } from "react";

const Home: NextPage = () => {
  const [query, setQuery] = useState("");
  const [searched, setSearched] = useState(false);
  const {data: data, isLoading} = api.items.search.useQuery({ query });

  const itemsPerPage = 10;
  return (
    <>
      <Head>
        <title>Price Guide</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <img width="200px" style={{margin:"15px"}} src="https://yoworld.com/images/title_yoworld_logo.png"></img>
      <br/><br/>
      <Center>
        <Heading size="md" fontWeight="500">Search for an item</Heading>
        
      </Center>
      <Center mt="1rem">
         <Input width="300px" placeholder="Item name" onChange={(e) => {
          setSearched(true)
          setQuery(e.currentTarget.value)}} />
      </Center>
     
     {/*** Results */}
     {isLoading && (
       <Center mt="3rem">
      <Spinner color="red" size="xl"/>
    </Center>
     )}

     {!isLoading && searched && (
        <Container maxW="container.xl" mt="3rem">
          {data?.items?.map((item) => (
            <Link href="#" key={item.id}>
              <Center>
              <Flex
                className={styles.item}
                p="1rem"
                borderWidth="1px"
                borderRadius="lg"
                alignItems="center"
                cursor="pointer"
                width="50%"
              >

                <img
                  width="100px"
                  height="100px"
                  src={item.imageUrl}
                  alt={item.name}
                />
                <Spacer />
                <Text fontSize="lg" fontWeight="500">
                  {item.name}
                </Text>
                <Spacer />
                <Text fontSize="lg" fontWeight="500">
                  {item.price} coins
                </Text>
              </Flex>
              </Center>
            </Link>
          )
          )}
        </Container>
     )}
   
     
    </>
  );
};

export default Home;
